#######################
# RE: DRAGON v1.0.0   #
#######################
# configuration file  #
#######################

# leave this empty, or write "null", to disable
egg-drop-message: "&8[&dRE:Dragon&8] &7The dragon egg has dropped at &b%drop-location%&7!"

# this is what the coordinates will look like
drop-location-format: "&bX:%x%&7, &bY:%y%&7, &bZ:%z%"
